services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: apresentacao
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:  # Certifique-se de que 'app' esteja dentro de 'services'
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mais_delas
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/apresentacao
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
